#include "dominion.h"

int main () {
  struct gameState G;
  int k[10] = {adventurer, minion, village, smithy, gardens, mine,
	       treasure_map, council_room, great_hall, steward};
  initializeGame(2, k, 1, &G);
  
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  endTurn(&G);
  buyCard(0, &G);
  endTurn(&G);
  endTurn(&G);
  buyCard(-198198191, &G);
}
