######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 26 11:56:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LabelClicked.h LabelWidget.h
SOURCES += moo.cpp
